import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../components/Header";
import NewFooter from "../../components/PYQ/NewFooter";
import Aside from "../../components/Aside";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className} >
      <header ><Header/></header>
      <div>
      <Aside/>
        <main className="mt-24 bg-white z-10">
        {children}
        </main>
        </div>
        <footer className="z-10 relative">
       <NewFooter/>
        </footer>
        </body>
    </html>
  );
}
